### ISSUE TITLE
Use Semantics action

### ISSUE THREAD

**Issue by jowi24** [CrazyIvan359/openhab-helper-libraries#10]
**Is your feature request related to a problem? Please describe.**
OH3 exposes a new action called "Semantics" to access attributes of the new OH3 semantic model, e.g. locations, equipments, points... I tried to use that action in Jython but it failed out of the box (see below).

**Describe the solution you'd like**
It would be great to use Sematics action like other actions:
`from core.actions import Semantics`
`...`
`locationItem = Semantics.getLocation(pointItem)`

**Describe alternatives you've considered**
I tried to import the action directly, but failed:
`from org.openhab.core.model.script.actions import Semantics`
`Error during evaluation of script 'file:/etc/openhab/automation/jsr223/python/personal/tests.py': ImportError: cannot import name Semantics `

**Additional context**
Do you know what steps are required to use that new action? Is it required to extend `automation/lib/python/core/actions.py`?

**Comment by CrazyIvan359** [comment]
I'm not familiar with this action, but the actions don't really need much help from the libraries. I'm going to guess it's an openHAB Core action so we'd need to add it in `actions.py` as you suggest.

**Comment by CrazyIvan359** [comment]
Looks like it's a service, not an action, that makes it a little harder. There is already a service getter in the OSGi module of the libraries, a new `semantics.py` file could be created and a wrapper added to acquire and interface to this service.

**Comment by jowi24** [comment]
Thank you for commenting my question. I realized that the Semantics action I tried to import is not yet avaible in https://github.com/openhab/openhab-core/tree/3.0.x but only in OH master branch... Thats why I failed :-(

**Comment by CrazyIvan359** [comment]
If you can find the action code itself and give me a link I can check if you will be able to use it without modifying the libraries.

**Comment by jowi24** [comment]
I just upgraded to OpenHAB 3.1.0M2 milestone release and could succesfully use the following code without need to modify your library :-)

`from org.openhab.core.model.script.actions import Semantics`
`locationItem = Semantics.getLocation(pointItem)`

Thanks for your help!

**Comment by CrazyIvan359** [comment]
I will add this to the `core/actions.py` module so that it can be use as simply `from core.actions import Semantics`

**Comment by janwo** [comment]
> I will add this to the `core/actions.py` module so that it can be use as simply `from core.actions import Semantics`

This works for me already. I have cloned the current branch.

**Comment by CrazyIvan359** [comment]
@janwo are you using `from actions import semantics` or `from core.actions import semantics`?

**Comment by janwo** [comment]
`from core.actions import semantics`
